### ISSUE TITLE
Your second test might fail with segfault because of Node version

### ISSUE THREAD

**Issue by kapooostin** [JakeGinnivan/jest-image-snapshot#1]
I've just spent a day fighting with https://github.com/americanexpress/jest-image-snapshot/. It failed with SIGABRT no matter what.

The reason behind it was [incompatibility](https://github.com/lukeapage/pngjs/issues/95) of `pngjs` with Node v. 9.x.x. Downgrading to 8.9.x solved the issue.

So if you tried it on Node 9, check if downgrading could help.

**Comment by JakeGinnivan** [comment]
Thanks for the heads up on this one, would have hit it at some point I'm sure!

**Comment by kapooostin** [comment]
Hope, this’ll help!
